<?xml version="1.0" encoding="UTF-8"?>
<!--
    $Author: zhenwei.yin  
    $Date: 2013-4-11 下午13:36:21  
    $Revision: 1.0  
    $Purpose: 
-->
<bm:model xmlns:e="aurora.service.exception" xmlns:bm="http://www.aurora-framework.org/schema/bm" xmlns:f="aurora.database.features" alias="t1" baseTable="hls_bp_relation_type" defaultOrderBy="relation_type">
    <bm:fields>
        <bm:field name="relation_category" databaseType="VARCHAR2" datatype="java.lang.String" physicalName="RELATION_CATEGORY" prompt="HLS.RELATION_CATEGORY"/>
        <bm:field name="relation_category_desc" datatype="java.lang.String" expression="(select hbr.description from hls_bp_relation_category hbr where hbr.relation_category = t1.relation_category)" forInsert="flase" forUpdate="false"/>
        <bm:field name="relation_type" databaseType="VARCHAR2" datatype="java.lang.String" physicalName="RELATION_TYPE" prompt="HLS.RELATION_TYPE"/>
        <bm:field name="description" databaseType="VARCHAR2" datatype="java.lang.String" physicalName="DESCRIPTION" prompt="HLS.DESCRIPTION"/>
        <bm:field name="enabled_flag" databaseType="VARCHAR2" datatype="java.lang.String" physicalName="ENABLED_FLAG" prompt="HLS.ENABLED_FLAG"/>
    </bm:fields>
    <bm:features>
        <f:standard-who/>
    </bm:features>
    <bm:primary-key>
        <bm:pk-field name="relation_type"/>
    </bm:primary-key>
    <e:exception-descriptor-config>
        <e:exception-descriptor exception="java.sql.SQLException" handleClass="aurora.database.SQLExceptionDescriptor">
            <e:error-message code="1" message="HLS.HLS013_UNIQUE_ERROR"/>
        </e:exception-descriptor>
    </e:exception-descriptor-config>
</bm:model>
